services:
  - type: web
    name: seea-vision
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flowstate_ai.py
    envVars:
      - key: PORT
        value: 10000
