services:
  - type: web
    name: flowstate-ai
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install gunicorn==21.2.0
      pip install -e .
    startCommand: |
      gunicorn --worker-tmp-dir /dev/shm flowstate_ai:app
