buildCommand: |
  python -m pip install --upgrade pip
  python -m pip install setuptools==68.0.0 wheel
  python -m pip install gunicorn==21.2.0 --ignore-installed --force-reinstall
  python -m pip install -e .
  python -c "import gunicorn; print(f'GUNICORN LOCATION: {gunicorn.__file__}')"
