services:
  - type: web
    name: flowstate-ai
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install gunicorn==21.2.0
      pip install -r requirements.txt
      python -c "import os; print('\nCurrent directory:', os.getcwd(), '\nFiles:', os.listdir())"
    startCommand: |
      python -m gunicorn --bind :$PORT flowstate_ai:app
