services:
  - type: web
    name: flowstate-ai
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip show gunicorn
    startCommand: gunicorn flowstate_ai:app
    envVars:
      - key: OPENAI_API_KEY
        description: "Your OpenAI API key"
        required: true
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.13
