services:
  - type: web
    name: flowstate-ai
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install gunicorn==21.2.0
      python -m pip install -e .
    startCommand: |
      python -m gunicorn --bind :$PORT flowstate_ai:app
