services:
  - type: web
    name: flowstate-ai
    env: python
    buildCommand: |
      python -m venv /opt/render/project/.venv
      . /opt/render/project/.venv/bin/activate
      pip install --upgrade pip setuptools wheel
      pip install gunicorn==21.2.0
      pip install -e .
    startCommand: |
      . /opt/render/project/.venv/bin/activate
      gunicorn --bind :$PORT flowstate_ai:app
